In [1]:
import pandas as pd

In [2]:
df_test = pd.read_csv("GUIDE_Test.csv")

C:\Users\rahul\AppData\Local\Temp\ipykernel_23200\1483317521.py:1: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df_test = pd.read_csv("GUIDE_Test.csv")

In [3]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4147992 entries, 0 to 4147991
Data columns (total 46 columns):
 #   Column              Dtype
---  ------              -----
 0   Id                  int64
 1   OrgId               int64
 2   IncidentId          int64
 3   AlertId             int64
 4   Timestamp           object
 5   DetectorId          int64
 6   AlertTitle          int64
 7   Category            object
 8   MitreTechniques     object
 9   IncidentGrade       object
 10  ActionGrouped       object
 11  ActionGranular      object
 12  EntityType          object
 13  EvidenceRole        object
 14  DeviceId            int64
 15  Sha256              int64
 16  IpAddress           int64
 17  Url                 int64
 18  AccountSid          int64
 19  AccountUpn          int64
 20  AccountObjectId     int64
 21  AccountName         int64
 22  DeviceName          int64
 23  NetworkMessageId    int64
 24  EmailClusterId      float64
 25  RegistryKey         int64
 26  RegistryValueName   int64
 27  RegistryValueData   int64
 28  ApplicationId       int64
 29  ApplicationName     int64
 30  OAuthApplicationId  int64
 31  ThreatFamily        object
 32  FileName            int64
 33  FolderPath          int64
 34  ResourceIdName      int64
 35  ResourceType        object
 36  Roles               object
 37  OSFamily            int64
 38  OSVersion           int64
 39  AntispamDirection   object
 40  SuspicionLevel      object
 41  LastVerdict         object
 42  CountryCode         int64
 43  State               int64
 44  City                int64
 45  Usage               object
dtypes: float64(1), int64(30), object(15)
memory usage: 1.4+ GB

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_test.head(10)

,Id,OrgId,IncidentId,AlertId,Timestamp,DetectorId,AlertTitle,Category,MitreTechniques,IncidentGrade,ActionGrouped,ActionGranular,EntityType,EvidenceRole,DeviceId,Sha256,IpAddress,Url,AccountSid,AccountUpn,AccountObjectId,AccountName,DeviceName,NetworkMessageId,EmailClusterId,RegistryKey,RegistryValueName,RegistryValueData,ApplicationId,ApplicationName,OAuthApplicationId,ThreatFamily,FileName,FolderPath,ResourceIdName,ResourceType,Roles,OSFamily,OSVersion,AntispamDirection,SuspicionLevel,LastVerdict,CountryCode,State,City,Usage
0,1245540519230,657,11767,87199,2024-06-04T22:56:27.000Z,524,563,LateralMovement,T1021;T1047;T1105;T1569.002,BenignPositive,NaN,NaN,User,Impacted,98799,138268,360606,160396,2610,3699,425863,863,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,Suspicious,Suspicious,242,1445,10630,Private
1,1400159342154,3,91158,632273,2024-06-03T12:58:26.000Z,2,2,CommandAndControl,NaN,BenignPositive,NaN,NaN,Machine,Impacted,1239,138268,360606,160396,441377,673934,425863,453297,2833,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,0,0,NaN,Suspicious,Suspicious,242,1445,10630,Public
2,1279900255923,145,32247,131719,2024-06-08T03:20:49.000Z,2932,10807,LateralMovement,T1021;T1027.002;T1027.005;T1105,BenignPositive,NaN,NaN,Process,Related,98799,4296,360606,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,14,22,3586,NaN,NaN,5,66,NaN,Suspicious,Suspicious,242,1445,10630,Public
3,60129547292,222,15294,917686,2024-06-12T12:07:31.000Z,0,0,InitialAccess,T1078;T1078.004,FalsePositive,NaN,NaN,CloudLogonSession,Related,98799,138268,360606,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Public
4,515396080539,363,7615,5944,2024-06-06T17:42:05.000Z,27,18,Discovery,T1087;T1087.002,BenignPositive,NaN,NaN,User,Impacted,98799,138268,360606,160396,133549,673934,425863,136104,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,Suspicious,5,66,NaN,NaN,NaN,242,1445,10630,Public
5,670014899930,0,238,378946,2024-06-06T08:10:50.000Z,0,0,InitialAccess,T1078;T1078.004,TruePositive,NaN,NaN,User,Impacted,98799,138268,360606,160396,2544,3392,2558,2696,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Public
6,1194000913330,133,105333,732769,2024-06-15T04:06:55.000Z,3,4,SuspiciousActivity,NaN,BenignPositive,NaN,NaN,Machine,Impacted,593,138268,360606,160396,441377,673934,425863,453297,1794,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,Suspicious,Suspicious,242,1445,10630,Private
7,678604832796,6,2461,1523,2024-05-26T11:48:38.000Z,17,1265,Impact,NaN,BenignPositive,NaN,NaN,Ip,Related,98799,138268,10862,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Public
8,618475292265,7,5177,1815,2024-05-25T17:57:20.000Z,21,528,Impact,NaN,FalsePositive,NaN,NaN,Ip,Related,98799,138268,128,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Public
9,438086667998,100,7060,9787,2024-06-02T05:46:22.000Z,72,53,Impact,NaN,BenignPositive,NaN,NaN,Ip,Related,98799,138268,473,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Public

In [6]:
df_test['hour'] = pd.to_datetime(df_test['Timestamp']).dt.hour

In [7]:
df_test.drop(["MitreTechniques","ActionGrouped","ActionGranular","ThreatFamily","ResourceType","Roles","AntispamDirection","SuspicionLevel","LastVerdict","EmailClusterId"],axis=1,inplace=True)

In [8]:
df_test.drop(["Id","IncidentId","AlertId","DetectorId","AlertTitle","DeviceId","Sha256","IpAddress","Url","ApplicationName","OAuthApplicationId","FileName","FolderPath","ResourceIdName","OSFamily","OSVersion","CountryCode","State","City"],axis=1,inplace=True)

In [9]:
df_test.drop(["AccountSid","AccountUpn","AccountObjectId","AccountName","DeviceName","NetworkMessageId","RegistryKey","RegistryValueName","RegistryValueData","ApplicationId","Timestamp"],axis=1,inplace=True)

In [10]:
df_test.drop(["Usage"],axis=1,inplace=True)

In [11]:
df_test

,OrgId,Category,IncidentGrade,EntityType,EvidenceRole,hour
0,657,LateralMovement,BenignPositive,User,Impacted,22
1,3,CommandAndControl,BenignPositive,Machine,Impacted,12
2,145,LateralMovement,BenignPositive,Process,Related,3
3,222,InitialAccess,FalsePositive,CloudLogonSession,Related,12
4,363,Discovery,BenignPositive,User,Impacted,17
...,...,...,...,...,...,...
4147987,262,InitialAccess,BenignPositive,User,Impacted,3
4147988,1323,InitialAccess,BenignPositive,User,Impacted,19
4147989,47,CommandAndControl,FalsePositive,Ip,Related,0
4147990,70,InitialAccess,BenignPositive,Mailbox,Impacted,16
4147991,227,InitialAccess,TruePositive,Mailbox,Impacted,18

In [12]:
df_test.to_csv("Final_test.csv",index=False)

In [13]:
df_test

,OrgId,Category,IncidentGrade,EntityType,EvidenceRole,hour
0,657,LateralMovement,BenignPositive,User,Impacted,22
1,3,CommandAndControl,BenignPositive,Machine,Impacted,12
2,145,LateralMovement,BenignPositive,Process,Related,3
3,222,InitialAccess,FalsePositive,CloudLogonSession,Related,12
4,363,Discovery,BenignPositive,User,Impacted,17
...,...,...,...,...,...,...
4147987,262,InitialAccess,BenignPositive,User,Impacted,3
4147988,1323,InitialAccess,BenignPositive,User,Impacted,19
4147989,47,CommandAndControl,FalsePositive,Ip,Related,0
4147990,70,InitialAccess,BenignPositive,Mailbox,Impacted,16
4147991,227,InitialAccess,TruePositive,Mailbox,Impacted,18